kind: pipeline
name: default

steps:
- name: test
  image: python:3.7-alpine
  commands:
  - pip install . > /dev/null
  - pip install pytest > /dev/null
  - pytest  --disable-warnings
- name: bump
  image: xplugins/bump
  settings:
    github_token: 
      from_secret: github_token
    versionfile: VERSION
- name: pypi_publish
  image: plugins/pypi
  settings:
    username: xmorse
    password:
      from_password: pypi_password